dist: xenial
language: python
python:
    - '3.7'
before_script:
    - pip install pipenv
    - pipenv install --dev
env:
    - DB_USER='user'
    - DB_PASS='pass'
    - DJANGO_SETTINGS_MODULE='settings'
services:
    - postgresql
script:
    - pipenv run python manage.py test
branches:
    only:
        - staging
